### ISSUE TITLE
"make html" error

### ISSUE THREAD

**Issue by kshitij10496** [kgpmnc/blog-source-code#1]
After updating the source code with a `.md` file, I tried to run `make html`.
I got a `make: *** No rule to make target 'html'.  Stop.` error.
What extension am I supposed to use in order to update the blog (`.html` or `.md`) ?

**Comment by OrkoHunter** [comment]
Are you sure you are running it from the correct path? There should be a `makefile` to run `make html`.

**Comment by OrkoHunter** [comment]
@kshitij10496 **Ping**

**Comment by OrkoHunter** [comment]
It's about time that the blog needs update.
